
version: 2

models:
  - name: weekly_top_journals
    description: "A starter dbt model"
    columns:
      - name: week
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
